### ISSUE TITLE
Roadmap pour le CDCF

### ISSUE THREAD

**Issue by yoanlcq** [imac2018-3d/test-github-projects#1]
_On peut éditer ce post pour mettre à jour la liste à tout moment._

** Je mentionne des gens, mais c'est juste pour donner l'exemple. Tout ceci n'est qu'un test !! **

- [ ] Description High-level du projet @Hellowizz 
- [ ] Les use cases @yoanlcq
  - [ ] Le menu pause
  - [ ] Les combats
  - [ ] etc... 
- [ ] Mettre en forme
- ????

**Comment by yoanlcq** [comment]
Mais il manque plein d'items !

**Comment by yoanlcq** [comment]
:100:
